# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20170220_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
