# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20170224_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_card_id',
            field=models.CharField(default='n-a', max_length=256),
        ),
    ]
