# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_profile_member_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='access_level',
        ),
        migrations.AddField(
            model_name='accesslevel',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.Machine'),
        ),
        migrations.AddField(
            model_name='accesslevel',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.Profile'),
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='access_level',
            field=models.CharField(default='NONE', max_length=10),
        ),
    ]
